modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="toggle_offhand"
version="${version}"
displayName="Toggle Offhand"
authors="leeineian"
description="Minimalist client mod to toggle rendering the offhand with a keybind."

[[mixins]]
config="toggle_offhand.mixins.json"

[[dependencies.toggle_offhand]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="NONE"
side="CLIENT"
